### ISSUE TITLE
tf2onnx - how?

### ISSUE THREAD

**Issue by AndreV84** [Nomikxyz/diabetic-retinopathy-screening#4]
could you help out figuring flags for converting the retrained.pb to onnx, please?
https://forums.developer.nvidia.com/t/implementing-deepstream-trt-integration-by-intels-scenario/153553

**Comment by javathunderman** [comment]
Hi there, 

This project is quite old at this point - much of the code hasn't been touched in about 3 years and there have been significant revisions made to the underlying APIs since then. At some point, I will probably update this project and add new features to it, but in the meantime, I highly suggest following [Google's image classifier tutorial](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning_with_hub.ipynb). Training MobileNet/ImageNet on diabetic retinopathy images should be fairly straightfoward if you follow that tutorial (basically swap the dataset they provide for the DR dataset). 

Sorry that I can't be more helpful. Please let me know if you have other questions - I'll try to answer as much as I can. Thanks.

**Comment by AndreV84** [comment]
Thank you for following up!
I shall try "MobileNet/ImageNet on diabetic retinopathy images"
I will post question sa thy emerge if you do not mind.

**Comment by AndreV84** [comment]
@javathunderman ,
If I setup access to a cloud instance with dGPU,
could you try to train a model on it, please?
So that it will be an updated model?
So that it could be possible further to approach integrating it into TensorRT with further integration into DeepStream?
Reference threads
https://forums.developer.nvidia.com/t/implementing-deepstream-trt-integration-by-intels-scenario/153553
https://forums.developer.nvidia.com/t/given-there-is-engine-file-h5-how-to-incorporate-it-into-deepstream/145401/35
